### ISSUE TITLE
Tizen installation failed

### ISSUE THREAD

**Issue by ayoisaiah** [kamildzi/Tizen4Docker#17]
While installing Tizen studio, I got this error:

![image](https://user-images.githubusercontent.com/13372163/89729268-db8b2680-da2b-11ea-91a0-a05e693c9b59.png)

And now restarting the script shows this error:

![image](https://user-images.githubusercontent.com/13372163/89729259-c0b8b200-da2b-11ea-9697-4c84856333ea.png)

How can I restart the installation process?

**Comment by kamildzi** [comment]
Hello, 

In order to restart the installation process, you will need to wipe the data from following two directories: 
- `LOCAL_TIZEN_STUDIO_DIRECTORY` 
- `LOCAL_TIZEN_STUDIO_DATA_DIRECTORY` (optional, but recommended)

These are the directories that you have configured in your `.env` file: 
![obraz](https://user-images.githubusercontent.com/12057520/89743496-eda8ab80-daa3-11ea-9091-70b5382a0fda.png)

Please make sure to remove everything, **including the hidden files**. 
If there are any leftovers from previous installation, the script will try to launch the IDE. 
If the directories are empty, then a clean installation will start out (only the IDE, docker image will stay untouched).

**Comment by ayoisaiah** [comment]
Thank you @kamildzi

**Comment by kamildzi** [comment]
You are welcome. :)
